[package]
name = "sub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_data = { path = "../common_data/"}
rscam = "0.5.5"
wiringpi = "0.2.4"
